<?xml version="1.0"?>
<robot name="ensenso_camera" xmlns:xacro="http://www.ros.org/wiki/xacro">

<material name="Ensenso/Blue">
  <color rgba="0.1 0.1 1.0 1.0"/>
</material>

<material name="Ensenso/Black">
  <color rgba="0.0 0.0 0.0 1.0"/>
</material>

  <xacro:macro name="ensenso_N3x_Series" params="name margin:=0.03">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0.00 0.0 0.0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/N30-602-16.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="-0.0085 0.00 0.026"/>
        <geometry>
          <box size="${margin+0.192} ${margin+0.050} ${margin+0.052}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lense_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.05 0.00 0.05" rpy=" 0 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>

  </xacro:macro>

  <xacro:macro name="ensenso_N4x_Series" params="name margin:=0.03">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0.00 0.0 0.0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/N4x-xxx.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <collision>
        <origin rpy="0 0 0" xyz="-0.0085 0.00 0.026"/>
        <geometry>
          <box size="${margin+0.192} ${margin+0.050} ${margin+0.052}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lense_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.05 0.00 0.05" rpy=" 0 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>

  </xacro:macro>


  <xacro:macro name="ensenso_X200_Series" params="name margin:=0.03 radius_lens_sensor:=0.02 length_lens_sensor:=0.05">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-5CP-200.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="-0.1067 ${0.036+length_lens_sensor/2.0} 0.033" rpy="${-pi/2} 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0.1067 ${0.036+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0 ${0.04+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>

      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 ${0.0005+length_lens_sensor/2} 0.033"/>
        <geometry>
          <box size="${margin+0.24350} ${margin+0.08+length_lens_sensor} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lens_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.1067 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>

  </xacro:macro>


  <xacro:macro name="ensenso_X200_xFA_Series" params="name margin:=0.03 radius_lens_sensor:=0.02 length_lens_sensor:=0.05">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-xFA-200.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="-0.117 ${0.031+length_lens_sensor/2.0} 0.033" rpy="${-pi/2} 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0.117 ${0.031+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0 ${0.041+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 ${-0.004+length_lens_sensor/2} 0.033"/>
        <geometry>
          <box size="${margin+0.2870} ${margin+0.09+length_lens_sensor} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lens_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.117 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>
  </xacro:macro>




  <xacro:macro name="ensenso_X400_Series" params="name margin:=0.03 radius_lens_sensor:=0.02 length_lens_sensor:=0.05">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-5CP-400.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="-0.2109 ${0.036+length_lens_sensor/2.0} 0.033" rpy="${-pi/2} 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0.2109 ${0.036+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0 ${0.04+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 ${0.0005+length_lens_sensor/2} 0.033"/>
        <geometry>
          <box size="${margin+0.4515} ${margin+0.08+length_lens_sensor} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lens_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.2109 0.036 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>
  </xacro:macro>

  <xacro:macro name="ensenso_X400_xFA_Series" params="name margin:=0.03 radius_lens_sensor:=0.02 length_lens_sensor:=0.05 radius_lens_projector:=0.02 length_lens_projector:=0.05">

    <link name="${name}">
      <visual>
        <origin rpy="0 0 0" xyz="0 0 0"/>
        <geometry>
          <mesh filename="package://ensenso_description/stl_meshes/X3x-xFA-400.stl"/>
        </geometry>
        <material name="Ensenso/Blue"/>
      </visual>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="-0.22125 ${0.031+length_lens_sensor/2.0} 0.033" rpy="${-pi/2} 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0.22125 ${0.031+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <xacro:objective radius="${radius_lens_sensor}" length_tube="${length_lens_sensor}">
        <origin xyz="0 ${0.041+length_lens_sensor/2.0} 0.033" rpy="-1.570796 0 0"/>
      </xacro:objective>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 ${-0.004+length_lens_sensor/2} 0.033"/>
        <geometry>
          <box size="${margin+0.4950} ${margin+0.09+length_lens_sensor} ${margin+0.066}"/>
        </geometry>
      </collision>
      <collision>
        <origin rpy="0.0 0.0 0.0" xyz="0.0 -0.004 0.033"/>
        <geometry>
          <box size="${margin+0.4950} ${margin+0.09} ${margin+0.066}"/>
        </geometry>
      </collision>
    </link>

    <!-- Left lens -->
    <joint name="${name}_left_lens_joint" type="fixed">
      <parent link="${name}"/>
      <child link="${name}_left_lens_frame"/>
      <origin xyz="-0.22125 0.031 0.033" rpy="-1.570796 0 0"/>
    </joint>
    <link name="${name}_left_lens_frame"/>
  </xacro:macro>


  <xacro:macro name="objective" params="radius length_tube *origin">
      <visual>
        <xacro:insert_block name="origin" />
        <geometry>
          <cylinder length="${length_tube}" radius="${radius}"/>
        </geometry>
        <material name="Ensenso/Black"/>
      </visual>
  </xacro:macro>

</robot>